- package:
  - name: frontrow-app
  - section:
    - name: test:doctest
    - message:
      - name: Redundant build-depends entry
      - depends: text
- package:
  - name: jobs
  - section:
    - name: test:spec
    - message:
      - name: Weeds exported
      - module:
        - name: TestImport
        - identifier: withAppTruncateUsing
- package:
  - name: fancy-api
  - section:
    - name: test:spec
    - message:
      - name: Redundant build-depends entry
      - depends: frontrow-app
    - message:
      - name: Weeds exported
      - module:
        - name: TestImport
        - identifier: getBaseFoundation
      - module:
        - name: TestImport
        - identifier: wipeDB
