---
name: advent
version: 0.1.0.0
github: "cdparks/advent"
license: BSD3
author: "Christopher Parks"
maintainer: "christopher.daniel.parks@gmail.com"
copyright: "2019 Christopher Parks"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/cdparks/advent#readme>

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies:
    - relude
    - pipes

executables:
  day1:
    main: Day1.hs
    source-dirs: executables
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
    - pipes
